# Generated by Django 6.0 on 2026-06-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='last_claim_date',
            field=models.DateTimeField(blank=True, help_text='When this pack was claimed (used for cooldown tracking).', null=True),
        ),
    ]
