# Generated by Django 6.0 on 2026-06-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_pack_last_claim_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='kind',
            new_name='type',
        ),
    ]
