# Generated by Django 6.0 on 2026-07-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_rename_kind_pack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_opened',
            field=models.BooleanField(default=False, help_text='Whether this pack has already been opened.'),
        ),
    ]
