# Generated by Django 6.0 on 2026-07-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_pack_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='max_rarity',
            field=models.FloatField(help_text='Maximum rarity for balls in this pack.', null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='min_rarity',
            field=models.FloatField(help_text='Minimum rarity for balls in this pack.', null=True),
        ),
    ]
