# Generated by Django 6.0 for app rename from 'packs' to 'ballsdex_packs'

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_pack_is_opened'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE packs_pack RENAME TO ballsdex_packs_pack;",
            reverse_sql="ALTER TABLE ballsdex_packs_pack RENAME TO packs_pack;",
        ),
    ]
