from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_pack_max_rarity_pack_min_rarity'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS packs_pack RENAME TO packs_packinstance;",
                    reverse_sql="ALTER TABLE IF EXISTS packs_packinstance RENAME TO packs_pack;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE packs_packinstance ADD COLUMN IF NOT EXISTS is_opened boolean DEFAULT FALSE;",
                    reverse_sql="ALTER TABLE packs_packinstance DROP COLUMN IF EXISTS is_opened;",
                ),
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS packs_pack (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        type varchar(100) NOT NULL UNIQUE,
                        min_rarity double precision NULL,
                        max_rarity double precision NULL
                    );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS packs_pack;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PackInstance',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('type', models.CharField(help_text='Type of the pack.', max_length=100)),
                        ('discord_id', models.BigIntegerField(help_text='Discord user ID.')),
                        ('last_claim_date', models.DateTimeField(blank=True, help_text='When this pack was claimed (used for cooldown tracking).', null=True)),
                        ('min_rarity', models.FloatField(help_text='Minimum rarity for balls in this pack.', null=True)),
                        ('max_rarity', models.FloatField(help_text='Maximum rarity for balls in this pack.', null=True)),
                        ('is_opened', models.BooleanField(default=False, help_text='Whether this pack has already been opened.')),
                    ],
                ),
                migrations.DeleteModel(
                    name='Pack',
                ),
                migrations.CreateModel(
                    name='Pack',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('type', models.CharField(help_text='Type of the pack.', max_length=100)),
                        ('min_rarity', models.FloatField(help_text='Minimum rarity for balls in this pack.', null=True)),
                        ('max_rarity', models.FloatField(help_text='Maximum rarity for balls in this pack.', null=True)),
                    ],
                ),
            ]
        )
    ]