from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packs", "0005_pack_max_rarity_pack_min_rarity"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE IF EXISTS packs_pack RENAME TO packs_packinstance;",
            reverse_sql="ALTER TABLE IF EXISTS packs_packinstance RENAME TO packs_pack;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE packs_packinstance ADD COLUMN IF NOT EXISTS is_opened boolean DEFAULT FALSE;",
            reverse_sql="ALTER TABLE packs_packinstance DROP COLUMN IF EXISTS is_opened;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS packs_pack (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type varchar(100) NOT NULL UNIQUE,
                min_rarity double precision NULL,
                max_rarity double precision NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS packs_pack;",
        ),
    ]