# Generated by Django 6.0 on 2026-07-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0006_packinstance_remove_pack_discord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='type',
            field=models.CharField(help_text='Type of the pack.', max_length=100, unique=True),
        ),
    ]
