# Generated by Django 6.0 on 2026-07-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0008_pack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='max_rarity',
            field=models.FloatField(blank=True, help_text='Maximum rarity for balls in this pack.', null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='min_rarity',
            field=models.FloatField(blank=True, help_text='Minimum rarity for balls in this pack.', null=True),
        ),
    ]
