# Generated by Django 6.0 on 2026-07-23 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0009_alter_pack_max_rarity_alter_pack_min_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinstance',
            name='max_rarity',
        ),
        migrations.RemoveField(
            model_name='packinstance',
            name='min_rarity',
        ),
        migrations.RemoveField(
            model_name='packinstance',
            name='type',
        ),
        migrations.AddField(
            model_name='pack',
            name='cooldown_seconds',
            field=models.IntegerField(default=86400, help_text='Cooldown between claims in seconds (e.g. 86400 for 1 day, 604800 for 1 week).'),
        ),
        migrations.AddField(
            model_name='pack',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this pack is active.'),
        ),
        migrations.AddField(
            model_name='packinstance',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='packs.pack'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(default='Unnamed Pack', help_text='Name of the pack.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pack',
            name='type',
            field=models.CharField(help_text='Type of the pack (in lowercase please).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='packinstance',
            name='last_claim_date',
            field=models.DateTimeField(blank=True, help_text='When this pack was claimed.', null=True),
        ),
    ]
